### ISSUE TITLE
Does this work with flow from directory?

### ISSUE THREAD

**Issue by wanx4910** [WittmannF/LRFinder#1]
I have seen many LR finders that require the X_train and Y_train to be defined manually but for large datasets that is about 40-50k images, the only method that doesn't crash the kernel is using flow from directory. Does your finder play nice with flow form directory? Where the labels are kind of defined implicitly by Image Data Generator.

**Comment by WittmannF** [comment]
Hey @wanx4910 ! It works with flow from directory! There's an example in the playground: https://github.com/WittmannF/LRFinder/blob/master/LRFinder_Playground.ipynb (just hit ctrl+F and search for flow_from_directory)
